export RSA_2048_PRIVATE='-----BEGIN RSA PRIVATE KEY-----
MIIJKAIBAAKCAgEAr1NSP62XkfrEvvlT9Xqn4ZHEXS8rHWikO0WQSsz+xEJBQyZ4
h/0BbREPbHIe+EOMEhFt4xCwUONOCJf+GmegUiRGWdSq1bEKCSv3SwCLWkE=
-----END RSA PRIVATE KEY-----'

export RSA_2048_PUBLIC='-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAr1NSP62XkfrEvvlT9Xqn
ss/r79JS12hso3PWJvuAebkCAwEAAQ==
-----END PUBLIC KEY----'
